name: Pull Request Builder

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x86
        vs-version: '[16.4,16.5)'
    - uses: actions/checkout@master
    - name: MSBuild
      run: msbuild /t:BH:Rebuild /p:Configuration=Release /p:SHA=${GITHUB_SHA::7} BH.sln
    - uses: actions/upload-artifact@v2
      with:
        name: BH.dll
        path: Release/BH.dll